name: Website Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACTION_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "16"
      - name: Setup Dependencies
        run: yarn install
      - name: Build Site
        run: yarn docs:build -d ./dist
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          branch: master
          repository: totalo/totalo.github.io
          force: true
          directory: ./dist