name: Website Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "16"
      - name: Setup Dependencies
        run: yarn install
      - name: Build Site
        run: yarn docs:build -d ./dist
      - name: Commit
        env:
          SSH_PRIVATE: ${{ secrets.SSH_PRIVATE }}
        run: |
          cd ./dist
          git config --local user.email totalo@apache.org
          git config --local user.name totalo
          git add .
          git commit -m "update:`date`"
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE" > ~/.ssh/id_rsa
          chmod 700 -R ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Deploy
        uses: ad-m/github-push-action@master
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          repository: totalo/totalo.github.io
          ssh: true
          branch: master
          force: true